services:
    fos_elastica.async_pager_persister:
        class: FOS\ElasticaBundle\Persister\AsyncPagerPersister
        arguments:
            - '@fos_elastica.pager_persister_registry'
            - '@fos_elastica.pager_provider_registry'
            - '@fos_elastica.messenger.bus'
        tags:
            - { name: fos_elastica.pager_persister, persisterName: async }
