services:
    fos_elastica.pager_provider.prototype.phpcr:
        class: FOS\ElasticaBundle\Doctrine\PHPCRPagerProvider
        abstract: true
        arguments:
            - '@doctrine_phpcr'
            - '@fos_elastica.doctrine.register_listeners'
            - ~ # model
            - [] # options

    fos_elastica.doctrine.register_listeners:
        class: FOS\ElasticaBundle\Doctrine\RegisterListenersService
        arguments:
            - '@event_dispatcher'

    fos_elastica.listener.prototype.phpcr:
        class: FOS\ElasticaBundle\Doctrine\Listener
        abstract: true
        arguments:
            - ~ # object persister
            - '@fos_elastica.indexable'
            - [] # configuration
            - null # logger

    fos_elastica.elastica_to_model_transformer.prototype.phpcr:
        class: FOS\ElasticaBundle\Doctrine\PHPCR\ElasticaToModelTransformer
        abstract: true
        arguments:
            - '@doctrine_phpcr'
            - ~ # model
            - [] # options
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]

    fos_elastica.manager.phpcr:
        class: FOS\ElasticaBundle\Doctrine\RepositoryManager
        arguments:
            - '@doctrine_phpcr'
            - '@fos_elastica.repository_manager'
