services:
    fos_elastica.model_to_elastica_transformer:
        class: FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer
        abstract: true
        arguments:
            - [] # options
            - '@event_dispatcher'
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]

    fos_elastica.model_to_elastica_identifier_transformer:
        class: FOS\ElasticaBundle\Transformer\ModelToElasticaIdentifierTransformer
        abstract: true
        arguments:
            - [] # options
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
